feat(issue-187): add a expand all button
coding-for-fun-org/frontend pull request #189
Opened 2024-02-29 06:43 UTC by jskurt

## Issue Link

[issue-187](https://github.com/kafelix496/coding-for-fun/issues/187)

## Notes

-

2024-03-01 13:08 UTC, kafelix496 reviewed
it's not a toggle button. when the user clicks the button, it just opens all of the repositories.

2024-03-02 00:50 UTC, jskurt commented
> it's not a toggle button. when the user clicks the button, it just opens all of the repositories.

So you mean use only Expand All? Isn't that better? Like open and close.

2024-03-02 01:02 UTC, kafelix496 commented
> > it's not a toggle button. when the user clicks the button, it just opens all of the repositories.
> 
> So you mean use only Expand All? Isn't that better? Like open and close.

I don't think the user wants to close it...

2024-03-02 05:32 UTC, jskurt commented
> > > it's not a toggle button. when the user clicks the button, it just opens all of the repositories.
> > 
> > 
> > So you mean use only Expand All? Isn't that better? Like open and close.
> 
> I don't think the user wants to close it...

okay :)

2024-03-02 16:47 UTC, kafelix496 requested changes
Nope, this is the wrong approach. Lift open status up

2024-03-02 16:48 UTC, kafelix496 commented
And also, create this PR base on the main branch.

2024-03-05 12:56 UTC, kafelix496 commented on src/modules/github/contexts/selected-pulls-provider.tsx
> +      }
we do not need payload here because we open all repos without any condition.

2024-03-06 13:24 UTC, kafelix496 commented on src/modules/github/components/bulk-pull-reviews/bulk-pull-reviews.tsx
> +      return
we do not need this condition here. if the `repos` variable is not defined, it will be covered in the reducer.

2024-03-06 13:24 UTC, kafelix496 commented on src/modules/github/components/bulk-pull-reviews/bulk-pull-reviews.tsx
> +        ></Button>
`<Button></Button>` -> `<Button />`

2024-03-06 13:24 UTC, kafelix496 commented on src/modules/github/contexts/selected-pulls-provider.tsx
> +        }))
Before we do it, let's check if all repos were already opened.

2024-03-06 14:18 UTC, kafelix496 approved these changes

2024-03-06 14:25 UTC, merged