feat(issue-38): use customized elements
coding-for-fun-org/frontend pull request #52
Opened 2024-01-09 01:37 UTC by jskurt

## Issue Link

[issue-38](https://github.com/kafelix496/coding-for-fun/issues/38)

## Notes

-

2024-01-09 11:51 UTC, kafelix496 reviewed
1. please link `label` and `checkbox` component using `id` and `htmlFor`.
2. let's make a little bit of the space. each checkbox connected and it doesn't look good.
3. remove the resize feature at the textbox component.

2024-01-09 11:53 UTC, kafelix496 commented on src/modules/github/components/pull-list-by-repo/pull-list-by-repo.tsx
> +            <ChevronRightIcon className={'ml-2'} onClick={handleRepoClick} />
there is no reason to add a curly bracket here. you can just use like `className="ml-2"`

2024-01-09 11:53 UTC, kafelix496 commented on src/modules/github/components/pull-review-form/pull-review-form.tsx
>        <div>
add some space between textarea and buttons

2024-01-09 11:53 UTC, kafelix496 commented on src/modules/github/components/pull-review-form/pull-review-form.tsx
>        </div>
add some space between buttons

2024-01-10 10:02 UTC, jskurt commented
> 1. please link `label` and `checkbox` component using `id` and `htmlFor`.
> 2. let's make a little bit of the space. each checkbox connected and it doesn't look good.
> 3. remove the resize feature at the textbox component.

1. finishied.
2. I cna't .................. help me..
3. where is it..?

2024-01-10 11:39 UTC, kafelix496 requested changes

2024-01-10 11:39 UTC, kafelix496 commented on src/modules/github/components/pull-list-by-repo/pull-list-by-repo.tsx
> +      <div className={'flex'}>
no need to use a curly bracket. just use a string.

2024-01-10 11:39 UTC, kafelix496 commented on src/modules/github/components/pull-list-by-repo/pull-list-by-repo.tsx
> +          id={`${repo}`}
> no need to use a curly bracket. just use a string.

same here

2024-01-10 11:39 UTC, kafelix496 commented on src/modules/github/components/pull-list-by-repo/pull-list-by-repo.tsx
> +        <Label htmlFor={`repoList.${repo}`} className="ml-2">
Wrong. this `htmlFor` value must be the same as `Checkbox` component id above (line 36)

2024-01-10 11:46 UTC, kafelix496 commented
> > 1. please link `label` and `checkbox` component using `id` and `htmlFor`.
> > 2. let's make a little bit of the space. each checkbox connected and it doesn't look good.
> > 3. remove the resize feature at the textbox component.
> 
> 1. finishied.
> 2. I cna't .................. help me..
> 3. where is it..?

1. good
2. create another issue for that. https://github.com/coding-for-fun-org/frontend/issues/59. do it later
3. google it.
<img width="490" alt="Screenshot 2024-01-10 at 6 46 03 AM" src="https://github.com/coding-for-fun-org/frontend/assets/41712713/ffd25b87-e16a-4a73-a747-3d746337b7fc">

2024-01-11 00:45 UTC, kafelix496 requested changes

2024-01-11 00:45 UTC, kafelix496 commented on src/elements/textarea/textarea.tsx
> +        style={{ resize: 'none' }}
check the tailwind css docs

https://tailwindcss.com/docs/resize

2024-01-11 10:42 UTC, kafelix496 requested changes

2024-01-11 10:42 UTC, kafelix496 commented on src/elements/textarea/textarea.tsx
> +          'resize-none flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focu
no, you should not touch the core element. use that class at the consuming level

2024-01-11 12:52 UTC, kafelix496 approved these changes
well done

2024-01-11 12:53 UTC, merged